// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDr84pbSEqpuV75EmYnnTG95FnkiHgs4Y',
    appId: '1:459743478908:web:c5174ffa7d07b5c9bcf5f9',
    messagingSenderId: '459743478908',
    projectId: 'cleancare-4be27',
    authDomain: 'cleancare-4be27.firebaseapp.com',
    storageBucket: 'cleancare-4be27.firebasestorage.app',
    measurementId: 'G-71YB8JNTLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6W8nU2nJf5ERx4TZr5leIkTlT5PXlBQY',
    appId: '1:459743478908:android:d9610bc5dc210281bcf5f9',
    messagingSenderId: '459743478908',
    projectId: 'cleancare-4be27',
    storageBucket: 'cleancare-4be27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkHG6gg3M2SUWQbTBe-OSJrvTm0rrPd5E',
    appId: '1:459743478908:ios:8238606712ba6458bcf5f9',
    messagingSenderId: '459743478908',
    projectId: 'cleancare-4be27',
    storageBucket: 'cleancare-4be27.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkHG6gg3M2SUWQbTBe-OSJrvTm0rrPd5E',
    appId: '1:459743478908:ios:8238606712ba6458bcf5f9',
    messagingSenderId: '459743478908',
    projectId: 'cleancare-4be27',
    storageBucket: 'cleancare-4be27.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDr84pbSEqpuV75EmYnnTG95FnkiHgs4Y',
    appId: '1:459743478908:web:e8efba6ab71766a9bcf5f9',
    messagingSenderId: '459743478908',
    projectId: 'cleancare-4be27',
    authDomain: 'cleancare-4be27.firebaseapp.com',
    storageBucket: 'cleancare-4be27.firebasestorage.app',
    measurementId: 'G-HZ2G0FX5LG',
  );
}